# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Image.LOAD_TRUNCATED_IMAGES": "DataLoading.ipynb",
         "ImageFile.LOAD_TRUNCATED_IMAGES": "DataLoading.ipynb",
         "SortedDL.new": "DataLoading.ipynb",
         "df_text": "DataLoading.ipynb",
         "get_filtered_image_files": "DataLoading.ipynb",
         "BlackCrop": "DataLoading.ipynb",
         "CropImageBlock": "DataLoading.ipynb",
         "CropText": "DataLoading.ipynb",
         "Remove1": "DataLoading.ipynb",
         "DALLE_dataloader": "DataLoading.ipynb",
         "create_reformer": "Reformer.ipynb"}

modules = ["data_loading.py",
           "reformer.py"]

doc_url = "/"

git_url = "https://github.com/marii-moe/text2animeimage/tree/master/"

def custom_doc_links(name): return None
