# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SortedDL.new": "DataLoading.ipynb",
         "df_text": "DataLoading.ipynb",
         "get_filtered_image_files": "DataLoading.ipynb",
         "open_image": "DataLoading.ipynb",
         "MyImageBlock": "DataLoading.ipynb",
         "Remove1": "DataLoading.ipynb",
         "DALLE_dataloader": "DataLoading.ipynb"}

modules = ["data_loading.py"]

doc_url = "/"

git_url = "https://github.com/marii-moe/text2animeimage/tree/master/"

def custom_doc_links(name): return None
