# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/Reformer.ipynb (unless otherwise specified).

__all__ = ['create_reformer']

# Cell
from PIL import Image
from pathlib import Path
from fastai.basics import *
from fastai.text.all import *
from transformers import ReformerModelWithLMHead, ReformerTokenizerFast,ReformerConfig
from fastai.callback.wandb import *
import wandb
from .data_loading import *

# Cell
def create_reformer():
    configuration = ReformerConfig(is_decoder=True)
    model=ReformerModelWithLMHead(configuration)
    model.reformer.embeddings.word_embeddings = nn.Embedding(2500+1+8192,256) #2500 for text, 1 for text-image seperator, and 8192 for image tokens
    #need 1+8192 for image tokens + seperator
    return model